name: daylily-prod

services:
  core:
    image: nyhryan/daylily-core
    ports:
      - "8080:8080"
    environment:
      - DAYLILY_DB_URL=jdbc:postgresql://db:5432/daylily-db
      - DAYLILY_DB_USER=${DAYLILY_DB_USER:?error}
      - DAYLILY_DB_PASSWORD=${DAYLILY_DB_PASSWORD:?error}
    depends_on:
      - db

  # PostgreSQL database
  db:
    image: postgres:alpine
    volumes:
        - db_data:/var/lib/postgresql/data
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${DAYLILY_DB_USER:?error}
      - POSTGRES_PASSWORD=${DAYLILY_DB_PASSWORD:?error}
      - POSTGRES_DB=daylily-db

  traefik:
    image: traefik:v3.4
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  db_data:
