name: daylily-dev

services:
  # PostgreSQL database
  db:
    image: postgres:alpine
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${DAYLILY_DB_USER:?error}
      - POSTGRES_PASSWORD=${DAYLILY_DB_PASSWORD:?error}
      - POSTGRES_DB=daylily-db

  # Tool for managing the database
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

  # traefik
  traefik:
    image: traefik:v3.4
    command:
      - "--providers.docker=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=INFO"
    ports:
      - "8082:80"
      - "8083:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
    db_data_dev:

networks:
  default:
    name: daylily-dev